import imgCruise from '../../assets/images/cruiseImage';

const cruiseData = [
  { 
    id: 1,
    name: 'Du thuyền Heritage Binh Chuan Cát Bà',
    rating: 4.9,
    reviews: '(12 đánh giá)',
    location: 'Vịnh Hạ Long',
    yearBuilt: 'Hạ thủy 2019 - Tàu vỏ Kim loại - 20 phòng',
    price: '4,150,000đ/khách',
    priceValue: 4150000,
    amenities: ['Cơ bản', 'Bảo gồm tại chỗ bỏ ăn', 'Quầy bar', 'Lên 24 giờ', 'Nhà hàng', '+10'],
    image: imgCruise.cruise1,
  },
  {
    id: 2,
    name: 'Du thuyền Orchid Trendy',
    rating: 5.0,
    reviews: '(4 đánh giá)',
    location: 'Vịnh Hạ Long',
    yearBuilt: 'Hạ thủy 2017 - Tàu vỏ Kim loại - 20 phòng',
    price: '4,150,000đ/khách',
    priceValue: 4150000,
    amenities: ['Phòng giãn', 'Bảo gồm tại chỗ bỏ ăn', 'Giáp biển', 'Quầy bar', 'Lên 24 giờ', '+7'],
    image: imgCruise.cruise2,
  },
  {
    id: 3,
    name: 'Du thuyền Milalux',
    rating: 5.0,
    reviews: '(2 đánh giá)',
    location: 'Vịnh Hạ Long',
    yearBuilt: 'Hạ thủy 2012 - Tàu vỏ Kim loại - 20 phòng',
    price: '3,200,000đ/khách',
    priceValue: 3200000,
    amenities: ['Phòng giãn', 'Giáp biển', 'Quầy bar', 'Lên 24 giờ', 'Nhà hàng', '+3'],
    image: imgCruise.cruise3,
  },
  {
    id: 4,
    name: 'Du thuyền Le Theatre',
    rating: 5.0,
    reviews: '(7 đánh giá)',
    location: 'Vịnh Hạ Long',
    yearBuilt: 'Hạ thủy 2019 - Tàu vỏ Kim loại - 21 phòng',
    price: '3,700,000đ/khách',
    priceValue: 3700000,
    amenities: ['Phòng giãn', 'Bảo gồm tại chỗ bỏ ăn', 'Quầy bar', 'Lên 24 giờ', 'Nhà hàng', '+8'],
    image: imgCruise.cruise4,
  },
  {
    id: 5,
    name: 'Du thuyền Indochine',
    rating: 5.0,
    reviews: '(4 đánh giá)',
    location: 'Vịnh Hạ Long',
    yearBuilt: 'Hạ thủy 2019 - Tàu vỏ Kim loại - 43 phòng',
    price: '4,125,000đ/khách',
    priceValue: 4125000,
    amenities: ['Bảo gồm tại chỗ bỏ ăn', 'Giáp biển', 'Quầy bar', 'Lên 24 giờ', 'Nhà hàng', '+7'],
    image: imgCruise.cruise5,
    },
    {
        id: 6,
        name: 'Du thuyền Stellar of the Seas',
        rating: 4.8,
        reviews: '(10 đánh giá)',
        location: 'Vịnh Hạ Long',
        yearBuilt: 'Hạ thủy 2018 - Tàu vỏ Kim loại - 22 phòng',
        price: '4,300,000đ/khách',
        priceValue: 4300000,
        amenities: ['Phòng giãn', 'Bảo gồm tại chỗ bỏ ăn', 'Quầy bar', 'Wi-Fi miễn phí', 'Nhà hàng', '+9'],
        image: imgCruise.cruise6,
      },
      {
        id: 7,
        name: 'Du thuyền Paradise Elegance',
        rating: 5.0,
        reviews: '(6 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2016 - Tàu vỏ Kim loại - 31 phòng',
        price: '4,500,000đ/khách',
        priceValue: 4500000,
        amenities: ['Trung tâm thể dục', 'Quầy bar', 'Có bể bơi ngoài trời', 'Nhà hàng', 'Điều hòa', '+6'],
        image: imgCruise.cruise7,
      },
      {
        id: 8,
        name: 'Du thuyền Mon Cheri',
        rating: 4.9,
        reviews: '(8 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2019 - Tàu vỏ Kim loại - 18 phòng',
        price: '3,900,000đ/khách',
        priceValue: 3900000,
        amenities: ['Phòng có bồn tắm', 'Wi-Fi miễn phí', 'Miễn phí kayaking', 'Ban công riêng', 'Sạc điện thoại', '+5'],
        image: imgCruise.cruise8,
      },
      {
        id: 9,
        name: 'Du thuyền Scarlet Pearl',
        rating: 4.7,
        reviews: '(5 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2020 - Tàu vỏ Kim loại - 23 phòng',
        price: '4,700,000đ/khách',
        priceValue: 4700000,
        amenities: ['Du thuyền 5 sao', 'Trà/cà phê trong tất cả các phòng', 'Nhìn ra biển', 'Cửa sổ từ sàn đến trần', '+4'],
        image: imgCruise.cruise9,
      },
      {
        id: 10,
        name: 'Du thuyền Athena Royal',
        rating: 5.0,
        reviews: '(3 đánh giá)',
        location: 'Vịnh Hạ Long',
        yearBuilt: 'Hạ thủy 2017 - Tàu vỏ Kim loại - 21 phòng',
        price: '4,200,000đ/khách',
        priceValue: 4200000,
        amenities: ['Bể bơi ngoài trời', 'Chỗ đỗ xe miễn phí', 'Miễn phí xe đưa đón', 'Wi-Fi', 'Két an toàn', '+3'],
        image: imgCruise.cruise10,
    },
    {
        id: 11,
        name: 'Du thuyền Capella',
        rating: 5.0,
        reviews: '(9 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2021 - Tàu vỏ Kim loại - 30 phòng',
        price: '4,600,000đ/khách',
        priceValue: 4600000,
        amenities: ['Phòng giãn', 'Miễn phí kayaking', 'Wi-Fi miễn phí', 'Trung tâm Spa & chăm sóc sức khỏe', 'Nhìn ra biển', '+8'],
        image: imgCruise.cruise11,
      },
      {
        id: 12,
        name: 'Du thuyền Ambassador',
        rating: 4.9,
        reviews: '(11 đánh giá)',
        location: 'Vịnh Hạ Long',
        yearBuilt: 'Hạ thủy 2022 - Tàu vỏ Kim loại - 46 phòng',
        price: '5,000,000đ/khách',
        priceValue: 5000000,
        amenities: ['Du thuyền 5 sao', 'Bể bơi ngoài trời', 'Quầy bar', 'Nhà hàng', 'Chỗ đỗ xe miễn phí', '+6'],
        image: imgCruise.cruise12,
      },
      {
        id: 13,
        name: 'Du thuyền La Regina',
        rating: 4.8,
        reviews: '(7 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2018 - Tàu vỏ Kim loại - 20 phòng',
        price: '3,800,000đ/khách',
        priceValue: 3800000,
        amenities: ['Ban công riêng', 'Phòng có bồn tắm', 'Miễn phí xe đưa đón', 'Cửa sổ từ sàn đến trần', 'Điều hòa', '+5'],
        image: imgCruise.cruise13,
      },
      {
        id: 14,
        name: 'Du thuyền Elite of the Seas',
        rating: 5.0,
        reviews: '(12 đánh giá)',
        location: 'Vịnh Hạ Long',
        yearBuilt: 'Hạ thủy 2023 - Tàu vỏ Kim loại - 40 phòng',
        price: '5,200,000đ/khách',
        priceValue: 5200000,
        amenities: ['Phòng không hút thuốc', 'Trà/cà phê trong tất cả các phòng', 'Nhìn ra biển', 'Sạc điện thoại', 'Két an toàn', '+4'],
        image: imgCruise.cruise14,
      },
      {
        id: 15,
        name: 'Du thuyền Heritage Cát Bà',
        rating: 4.7,
        reviews: '(6 đánh giá)',
        location: 'Vịnh Lan Hạ',
        yearBuilt: 'Hạ thủy 2020 - Tàu vỏ Kim loại - 25 phòng',
        price: '4,400,000đ/khách',
        priceValue: 4400000,
        amenities: ['Đi tuyến Lan Hạ', 'Có bể bơi ngoài trời', 'Wi-Fi miễn phí', 'Chỗ đỗ xe', 'Trung tâm thể dục', '+7'],
        image: imgCruise.cruise15,
      },
];

export default cruiseData;