const routes = {
    home: '/',
    cruise: '/cruise',
    flight: '/flight',
    hotel: '/hotel',
    business: '/business',
    blog: '/blog',
    contact: '/contact',
    about: '/about',
    terms: '/terms',
    privacy: '/privacy',
    usermanual: '/user-manual',
    payments: '/payments',
    regulations: '/regulations',
    faq: '/faq',
    notfound: '/404',
    search: '/search',
    cruiseDetail: '/cruise/:cruiseSlug',
    hotelDetail: '/hotel/:hotelSlug',
    auth: '/auth',
    signup: '/signup',
    forgetPwd: '/forgot-password',
};

export default routes;